map_bounding_volume:
  x_min: -20.0
  x_max: 20.0
  y_min: -20.0
  y_max: 20.0
  z_min: -1.5
  z_max: 1.5

evaluation_bounding_volume:
  x_min: -20.0
  x_max: 20.0
  y_min: -20.0
  y_max: 20.0
  z_min: -1.5
  z_max: 1.5

target_bounding_volume:
  x_min: -25.0
  x_max: 25.0
  y_min: -25.0
  y_max: 25.0
  z_min: -1.5
  z_max: 1.5
